// This file is @generated by prost-build.
/// All change request mappings tracked by jj-spice.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChangeRequests {
    /// Key: local jj bookmark name.
    #[prost(map = "string, message", tag = "1")]
    pub by_bookmark: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ForgeMeta,
    >,
}
/// Wrapper for the forge-specific oneof.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ForgeMeta {
    #[prost(oneof = "forge_meta::Forge", tags = "10")]
    pub forge: ::core::option::Option<forge_meta::Forge>,
}
/// Nested message and enum types in `ForgeMeta`.
pub mod forge_meta {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Forge {
        #[prost(message, tag = "10")]
        Github(super::GitHubMeta),
    }
}
/// GitHub Pull Request identity.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GitHubMeta {
    /// PR number
    #[prost(uint64, tag = "1")]
    pub number: u64,
    /// head ref pushed to GitHub
    #[prost(string, tag = "2")]
    pub source_branch: ::prost::alloc::string::String,
    /// base ref (e.g. "main")
    #[prost(string, tag = "3")]
    pub target_branch: ::prost::alloc::string::String,
    /// fork origin (e.g. "user/repo"), empty for same-repo
    #[prost(string, tag = "4")]
    pub source_repo: ::prost::alloc::string::String,
    /// target repo (e.g. "owner/repo"), empty for same-repo
    #[prost(string, tag = "5")]
    pub target_repo: ::prost::alloc::string::String,
    /// GraphQL node ID, for future mutation use
    #[prost(string, tag = "6")]
    pub graphql_id: ::prost::alloc::string::String,
    /// comment ID, for updating the stack trace in the Pull Request
    #[prost(uint64, optional, tag = "7")]
    pub comment_id: ::core::option::Option<u64>,
}
